name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./reservation/pom.xml
          mvn clean package -f ./consulting/pom.xml
          mvn clean package -f ./message/pom.xml
          mvn clean package -f ./dashboard/pom.xml
          mvn clean package -f ./feedback/pom.xml
          mvn clean package -f ./reprot/pom.xml

      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Reservation
        uses: docker/build-push-action@v4
        with:
          context: ./reservation
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reservation:latest
            ghcr.io/${{ github.repository }}/reservation:${{ github.ref_name }}
            
      - name: Docker Build and push for Consulting
        uses: docker/build-push-action@v4
        with:
          context: ./consulting
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/consulting:latest
            ghcr.io/${{ github.repository }}/consulting:${{ github.ref_name }}
            
      - name: Docker Build and push for Message
        uses: docker/build-push-action@v4
        with:
          context: ./message
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/message:latest
            ghcr.io/${{ github.repository }}/message:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
      - name: Docker Build and push for Feedback
        uses: docker/build-push-action@v4
        with:
          context: ./feedback
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/feedback:latest
            ghcr.io/${{ github.repository }}/feedback:${{ github.ref_name }}
            
      - name: Docker Build and push for Reprot
        uses: docker/build-push-action@v4
        with:
          context: ./reprot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/reprot:latest
            ghcr.io/${{ github.repository }}/reprot:${{ github.ref_name }}
            
