server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**, 
        - id: consulting
          uri: http://localhost:8084
          predicates:
            - Path=/consultings/**, 
        - id: message
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://localhost:8086
          predicates:
            - Path=, 
        - id: feedback
          uri: http://localhost:8087
          predicates:
            - Path=/feedbacks/**, 
        - id: reprot
          uri: http://localhost:8088
          predicates:
            - Path=/reprots/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: consulting
          uri: http://consulting:8080
          predicates:
            - Path=/consultings/**, 
        - id: message
          uri: http://message:8080
          predicates:
            - Path=, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: feedback
          uri: http://feedback:8080
          predicates:
            - Path=/feedbacks/**, 
        - id: reprot
          uri: http://reprot:8080
          predicates:
            - Path=/reprots/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
